name: Deploy_lambda_function
on:
  workflow_dispatch:
   inputs:
     TOKEN:
       type: 'choice'
       description: 'Choose the TOKEN'
       options:
         - 'dev'
         - 'postman'
     TESTING:
       type: boolean
       description: 'Do you want to test a lambda functon code?'
       default: true

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test array
        run: |
          readarray -t layer_list < <(jq -r .audience_upload.layers[] ./.github/workflows/lambda_var)
          declare -a layer_arn_list
          for var in ${layer_list[*]}; do layer_arn_list+=($(echo "layer_arn_is_$var")); done
          echo "my layers is: ${layer_arn_list[*]}"
