name: run_script

on:
  workflow_dispatch:
    inputs:
      SCRIPT_NAME:
        type: 'string'
        description: 'Fill in the script name'
      PARAMETERS:
        type: 'string'
        description: 'Fill in the script parameters'

env:
  AWS_REGION: us-east-1

jobs:
  build:
    name: run script
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.SPEARAI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SPEARAI_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: run script
        run: |
          aws ssm send-command --document-name AWS-RunShellScript --targets '[{"Key":"InstanceIds","Values":["i-03506613c27d0e236"]}]' \
          --parameters '{"workingDirectory":["/home/ec2-user/ssm_script/chainify"],"executionTimeout":["3600"],"commands":["git pull; cd ./scripts; python3 ${{ SCRIPT_NAME }} ${{ PARAMETERS }}"]}' \
          --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --cloud-watch-output-config '{"CloudWatchOutputEnabled":true,"CloudWatchLogGroupName":"ssm_scripts"}'

      - name: Show variables
        run: |
          echo "Hello world"
