name: Deploy_lambda_function
on:
  workflow_dispatch:
   inputs:
     TOKEN:
       type: 'choice'
       description: 'Choose the TOKEN'
       options:
         - 'dev'
         - 'postman'

env:
  FIRST: 'f2eb7bf0762d9530e5bf7a272fa86cefa4c67752'
  SECOND: '5e1d6d7290a821485dd36e72078065e47ae1a4f5'
  AWS_LAYER_ARN: "arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:3"

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v3
#        with:
#          ref: ${{ env.FIRST }}

      - name: run testing script
        run: |
          if "${{ inputs.TOKEN }}" == 'dev'
          then
            python ./testing.py ${{ secrets.DEV_TOKEN }}
          elif ${{ inputs.TOKEN }} == 'postman'
          then
            python ./testing.py ${{ secrets.POSTMAN_TOKEN }}
          fi

#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ env.SECOND }}
#
#      - name: print second
#        run: |
#          cat ./checkout
