name: Deploy_lambda_function
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: 'choice'
        description: 'Choose the environment'
        options:
          - 'production'
          - 'develop'
      ABSTRACT_NAME:
        type: 'choice'
        description: 'Choose the function'
        options:
          - 'DependenciesLayer'
          - 'UtilsLayer'


env:
  ABSTRACT_LAYER_NAME_1: "UtilsLayer"
  ABSTRACT_LAYER_NAME_2: "DependenciesLayer"
  AWS_LAYER_ARN: "arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:3"

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        run: |
          export FUNCTION_NAME=`jq -r '.${{ inputs.ABSTRACT_NAME }}.name.${{ inputs.ENVIRONMENT }}' \
          ./.github/workflows/lambda_var`
          export LAYER_NAME_1=`jq -r '.${{ env.ABSTRACT_LAYER_NAME_1 }}.name.${{ inputs.ENVIRONMENT }}' \
          ./.github/workflows/lambda_layer_var`
          export LAYER_NAME_2=`jq -r '.${{ env.ABSTRACT_LAYER_NAME_2 }}.name.${{ inputs.ENVIRONMENT }}' \
          ./.github/workflows/lambda_layer_var`
          echo "LAYER_NAME_1 is: ${LAYER_NAME_1}"
          echo "FUNCTION_NAME is: ${FUNCTION_NAME}"
          echo "LAYER_NAME_2 is: ${LAYER_NAME_2}"
