name: Deploy_lambda_function
on:
  workflow_dispatch:
#    inputs:
#      ABSTRACT_NAME:
#        type: 'choice'
#        description: 'Choose the function'
#        options:
#          - 'f2eb7bf0762d9530e5bf7a272fa86cefa4c67752'
#          - '5e1d6d7290a821485dd36e72078065e47ae1a4f5'

env:
  FIRST: 'f2eb7bf0762d9530e5bf7a272fa86cefa4c67752'
  SECOND: '5e1d6d7290a821485dd36e72078065e47ae1a4f5'
  AWS_LAYER_ARN: "arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:3"

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.FIRST }}

      - name: print first
        run: |
          cat ./checkout

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SECOND }}

      - name: print second
        run: |
          cat ./checkout
