name: Deploy_lambda_function
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: 'choice'
        description: 'Choose the environment'
        options:
          - 'production'
          - 'develop'
      ABSTRACT_NAME:
        type: 'choice'
        description: 'Choose the function'
        options:
          - 'DependenciesLayer'
          - 'UtilsLayer'


env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        run: |
          export LAYER_NAME=`jq -r '.${{ inputs.ABSTRACT_NAME }}.name.${{ inputs.ENVIRONMENT }}' \
          ./.github/workflows/lambda_layer_var`
          echo "name is: ${LAYER_NAME}"
