name: Deploy_lambda_function
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: 'choice'
        description: 'Choose the environment'
        options:
          - 'prod_env'
          - 'develop'
      FUNCTION_NAME:
        type: 'choice'
        description: 'Choose the function'
        options:
          - 'campanign_managmenet_prod-0044f30'
          - 'audience_upload_prod-69185d7'
          - 'appsync_authorizer_prod-61d0ecd'
          - 'audience_query_prod-3d5c860'
          - 'whitelisting_prod-f3f110f'
          - 'dashboard_prod-d45f806'


env:
  AWS_REGION: "us-east-1"
  prod_env: |
    {
      "one": "1",
      "two": "2"
    }



jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip it all up and upload
        run: |
          echo "${{ env.inputs.ENVIRONMENT }}"
          echo "${{ inputs.FUNCTION_NAME }}"
          echo ${{ fromJSON(env.prod_env.one) }}
