name: testing
on:
#  schedule:
#    - cron: '0 * * * *' # every hour on the hour
  workflow_dispatch:
    inputs:
#      ENVIRONMENT:
#        type: 'choice'
#        description: 'Choose the environment'
#        options:
#          - 'production'
#          - 'develop'
      APPSYNC_URL:
        type: 'string'
        description: 'AppSync URI'
      TOKEN:
        type: 'string'
        description: 'AppSync token'
      SLACK_WEBHOOK:
        type: 'string'


env:
  APPSYNC_DEV_URL: 'https://ry4dsee7fbgrvmkw67vybrra3i.appsync-api.us-east-1.amazonaws.com/graphql'
  APPSYNC_PROD_URL: 'https://dh3onmef7bhrhkyvw7uqeoczh4.appsync-api.us-east-1.amazonaws.com/graphql'
  PRODUCTION_TOKEN: ${{ secrets.PRODUCTION_TOKEN }}
  DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
jobs:
  deploy:
    name: testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: run testing script
        run: |
          pip3 install -r ./testing/requirements.txt
          echo 'Run script'
          python3 ./testing/apis_sanity_test.py ${{ inputs.TOKEN }} ${{ env.APPSYNC_DEV_URL }}

      - name: print error
        run:
          echo ${{ env.ERROR_MESSAGE }}

#      - name: Report Status
#        if: always()
#        uses: ravsamhq/notify-slack-action@v2
#        with:
#          status: ${{ job.status }}
#          notification_title: '{workflow} has {status_message}'
#        env:
#          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}

#      - name: set a github action status
#        run: |
#          if [ $ROLLBACK == 'True' ]
#          then
#            exit 1
#          fi
#  on_failure:
#    name: Send Email
#    runs-on: ubuntu-latest
#    steps:
#      - name: Email
#        uses: actions/email@v1
#        with:
##          to: 'shalevamiel@spearai.xyz, ronzaidman@spearai.xyz'
#          subject: 'Test Failure'
#          body: 'One or more tests have failed in the job ${{ env.GITHUB_JOB }}.
#            You can check the logs for more information at https://github.com/OWNER/REPO/actions/runs/${{ env.GITHUB_RUN_ID }}'
#
