name: Deploy_lambda_function
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: 'choice'
        description: 'Choose the environment'
        options:
          - 'production'
          - 'develop'
      ABSTRACT_NAME:
        type: 'choice'
        description: 'Choose the function'
        options:
          - 'campanign_managmenet'
          - 'audience_upload'
          - 'appsync_authorizer'
          - 'audience_query'
          - 'whitelisting'
          - 'dashboard'


env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    name: Upload lambda code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        run: |
          export FUNCTION_NAME=`jq -r '.${{ inputs.ABSTRACT_NAME }}.name.${{ inputs.ENVIRONMENT }}' \
          ./.github/workflows/lambda_var`
          export FUNCTION_PATH=`jq -r '.${{ inputs.ABSTRACT_NAME }}.path' \
          ./.github/workflows/lambda_var`
          echo "name is: ${FUNCTION_NAME}"
          echo "path is: ${FUNCTION_PATH}"
