application:
  name: test

deployments:
  - name: nginx
    replicas: 1
    containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
  - name: tomcat
    replicas: 1
    containers:
      - name: tomcat
        image: tomcat
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"

services:
  - name: nginx
    ports:
      - port: 80
        targetPort: 80
  - name: tomcat
    ports:
      - port: 80
        targetPort: 8080

ingress:
  rules:
    - http:
        - path: /nginx
          serviceName: test-nginx
          servicePort: 80
        - path: /tomcat
          serviceName: test-tomcat
          servicePort: 80
